name: Build EXE with PyInstaller

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build desktop exe
        run: |
          pyinstaller --onefile --windowed ^
            --add-data "templates;templates" ^
            --add-data "accounts.db;." ^
            desktop.py

      - name: Upload exe
        uses: actions/upload-artifact@v4
        with:
          name: my-exe
          path: dist/*.exe
